version: "3.1"
services:
  api-server:
    image: duchungho/swipe-api:446ab5a
    restart: always
    command: "swipe s"
    networks:
      - bridge
    ports:
      - 8000:8000
networks:
  bridge:
volumes:
  k8s:
