version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/x/socket"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 5
