version: "3.1"
services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./x/misc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./x/misc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - swipe_bridge
      
  swipe-server:
    image: duchungho/swipe-api:latest
    env_file:
      - .env.prod
    restart: always
    command: "swipe s"
    networks:
      - swipe_bridge
    ports:
      - 8000:8000

  swipe-worker:
    image: duchungho/swipe-api:latest
    env_file:
      - .env.prod
    restart: always
    networks:
      - swipe_bridge
    command: "swipe w"
    
networks:
  swipe_bridge:
volumes:
  pkg: