apiVersion: apps/v1
kind: Deployment
metadata:
  name: swipe-api-deployment
  labels:
    app: swipe-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swipe-api
  template:
    metadata:
      labels:
        app: swipe-api
    spec:
      containers:
        - image: duchungho/swipe-api:latest
          name: swipe-api-server
          env:
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: swipe-api-secret
                  key: swipe-api-host
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: swipe-api-secret
                  key: swipe-api-port
          command: ["swipe"]
          args: ["s"]
          ports:
            - containerPort: 8000
