name: build test api server

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build (linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build the Go application
        run: go build -ldflags="-s -w" -o ./bin/exe ./cmd

      - name: Remove binaries
        run: rm -rf bin

  test-common:
    needs: [build]
    name: unit test common
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Unit test - common
        run: bash hack/swipe run -t common

  test-posts:
    needs: [build]
    name: unit test posts module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Unit test - posts
        run: bash hack/swipe run -t posts

  test-products:
    needs: [build]
    name: unit test products module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Unit test - products
        run: bash hack/swipe run -t products
